### PR TITLE
Fix #29: handling of cookie max age property between Undertow and Pac4J

### LINKED ISSUE #29: Incompatible way cookie MaxAge is handled between Undertow and Pac4j
In Undertow, cookie max age is an `Integer` and in Pac4J, it is an `int` where `null` is represented as `-1`. This difference is not well handled in `UndertowWebContext`, e.g. a `NullPointerException` is thrown when cookie max age is null in Undertow.

I will submit a pull request asap.

### PR DESCRIPTION
**Pull request by slorion**

### CODE REVIEW

**Comment by leleuj** [comment]
Good catch! Thanks for the PR

**Comment by leleuj** [comment]
@slorion Can you confirm it's fixed using the version 2.0.1-SNAPSHOT? If so, I'll cut a new 2.0.1 release.

**Comment by slorion** [comment]
@leleuj Thank you for your quick response. I tested it with my application and it solved the issue.

**Comment by leleuj** [comment]
Perfect. I'll cut the release next week. Ping me if you don't get any news...

**Comment by leleuj** [comment]
I finally found some time today. The v2.0.1 release is available in the Maven central repository.

**Comment by slorion** [comment]
Super! Thank you again for your responsiveness!

**Pull request merged**
