### PR TITLE
Fix UndertowWebContext#getScheme() to return scheme, not protocol

### PR DESCRIPTION
**Pull request by Xaerxess**

### CODE REVIEW

**Comment by leleuj** [comment]
Good catch! I'll let you do more tests and I'll cut a release in a few days. Ping me if I forget.

**Comment by Xaerxess** [comment]
ping :)

**Comment by leleuj** [comment]
Indeed, I had forgotten ;-)

It's in progress, you should get a version 1.2.3 from the Maven central repository in a few hours...

**Comment by Xaerxess** [comment]
Thanks!

**Pull request merged**
